import type { Config } from "tailwindcss";

/**
 * Design tokens ported verbatim from the Stitch reference (stitch_examples/*.html).
 * These reproduce the reference visual system as a real build (no runtime CDN Tailwind).
 */
const config: Config = {
  content: ["./index.html", "./src/**/*.{ts,tsx}"],
  darkMode: "class",
  theme: {
    extend: {
      colors: {
        "on-secondary": "#ffffff",
        "on-surface": "#1a1c1b",
        "tertiary-fixed": "#ffdcbc",
        "on-tertiary-fixed-variant": "#683d00",
        "outline-variant": "#bfc7d0",
        primary: "#005c86",
        "secondary-container": "#62fae3",
        surface: "#f9f9f7",
        "inverse-surface": "#2f3130",
        "on-primary-fixed-variant": "#004c6e",
        "secondary-fixed": "#62fae3",
        "on-error-container": "#93000a",
        "on-tertiary-container": "#fff1e7",
        "on-surface-variant": "#40484f",
        "surface-container-high": "#e8e8e6",
        "error-container": "#ffdad6",
        "on-primary": "#ffffff",
        "on-background": "#1a1c1b",
        outline: "#707880",
        "on-error": "#ffffff",
        "surface-container": "#eeeeec",
        "on-secondary-container": "#007165",
        "tertiary-container": "#9f6109",
        "on-primary-fixed": "#001e2f",
        "surface-container-low": "#f4f4f2",
        "primary-fixed-dim": "#8aceff",
        "primary-container": "#0e76a8",
        "on-tertiary": "#ffffff",
        tertiary: "#7e4b00",
        "on-secondary-fixed": "#00201c",
        "surface-bright": "#f9f9f7",
        "surface-container-lowest": "#ffffff",
        "surface-tint": "#006491",
        "on-tertiary-fixed": "#2c1700",
        "surface-variant": "#e2e3e1",
        "tertiary-fixed-dim": "#ffb86b",
        "on-primary-container": "#ebf5ff",
        "secondary-fixed-dim": "#3cddc7",
        secondary: "#006b5f",
        background: "#f9f9f7",
        "on-secondary-fixed-variant": "#005047",
        "surface-container-highest": "#e2e3e1",
        error: "#ba1a1a",
        "inverse-on-surface": "#f1f1ef",
        "primary-fixed": "#c9e6ff",
        "inverse-primary": "#8aceff",
        "surface-dim": "#dadad8",
      },
      borderRadius: {
        DEFAULT: "0.125rem",
        lg: "0.25rem",
        xl: "0.5rem",
        full: "0.75rem",
      },
      spacing: {
        md: "24px",
        base: "8px",
        sm: "12px",
        lg: "48px",
        gutter: "20px",
        xs: "4px",
        "margin-desktop": "auto",
        xl: "80px",
        "margin-mobile": "16px",
        "max-width-content": "1120px",
      },
      maxWidth: {
        "max-width-content": "1120px",
      },
      fontFamily: {
        sans: ["Geist", "system-ui", "sans-serif"],
        "display-lg": ["Geist"],
        "display-lg-mobile": ["Geist"],
        "headline-md": ["Geist"],
        "body-md": ["Geist"],
        "label-caps": ["Geist"],
        "body-sm": ["Geist"],
        "title-sm": ["Geist"],
      },
      fontSize: {
        "display-lg": ["48px", { lineHeight: "56px", letterSpacing: "-0.02em", fontWeight: "700" }],
        "display-lg-mobile": ["32px", { lineHeight: "40px", letterSpacing: "-0.02em", fontWeight: "700" }],
        "headline-md": ["24px", { lineHeight: "32px", letterSpacing: "-0.01em", fontWeight: "600" }],
        "body-md": ["16px", { lineHeight: "24px", fontWeight: "400" }],
        "label-caps": ["12px", { lineHeight: "16px", letterSpacing: "0.05em", fontWeight: "600" }],
        "body-sm": ["14px", { lineHeight: "20px", fontWeight: "400" }],
        "title-sm": ["18px", { lineHeight: "24px", fontWeight: "600" }],
      },
    },
  },
  plugins: [],
};

export default config;
